on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: node/setup-node@0.x
      with:
        node-version: 16
    
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{secrets.ftp_server}}
        username: ${{secrets.ftp_username}}
        password: ${{secrets.ftp_password}}
